# Generated by Django 5.0.2 on 2024-04-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_descrição_cor_nome"),
    ]

    operations = [
        migrations.RenameField(
            model_name="acessorio",
            old_name="descrição",
            new_name="descricao",
        ),
    ]
