# Generated by Django 5.0.2 on 2024-04-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_descrição_acessorio_descricao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoria",
            old_name="descrição",
            new_name="descricao",
        ),
    ]
